.TH WMFU 1 "5 Apr 2007" "wmfu 1.0" "Linux User's Manual"
.SH NAME
wmfu \- a dockable system monitor
.SH SYNOPSIS
.B wmfu
[
.I options
]
.SH DESCRIPTION
.B wmfu
is a small dockapp that monitors system status.
.SH OPTIONS
.TP
\fB\-display\fP \fIdisplayname\fP
Attempt to run on the named X display.  In the absence of this option, the
display specified by the \fBDISPLAY\fP environment variable is used.
.TP
\fB\-h\fP, \fB\-\-help\fP
Print out a message describing available options.
.TP
\fB\-\-windowed\fP
Run in regular window.
.TP
\fB\-\-textmode\fP
Run in text mode.
.SH AUTHOR
Daniel Borca <dborca@yahoo.com>
