.TH WMSUN 1 "5 January 1999" 
.SH NAME
WMSUN \- Dockable WindowMaker SunRise/SunSet App
.SH SYNOPSIS
.B wmSun
[-h] [-display <Display>] [-lat <Latitude>] [-lon <Longitude>] [-td <TimeDiff>] [-date <yyyymmdd>]
.SH DESCRIPTION
.PP
wmSun displays the current day's Sun Rise and Set Times. You must enter your
LAtitude and Longitude correctly for it to work.
.SH OPTIONS
.TP
.B \-h
Display list of command-line options.
.TP
.B \-display <display>
Use an alternate X Display.
.TP
.B \-lat <Latitude>
Set latitude of observer.
.TP
.B \-lon <Longitude>
Set longitude of observer.
.TP
.B \-td <UT - LT>
Set the difference beteeen UT and LT. Useful when you want to show the
Sunrise/Sunset at a remote lat/lon without resetting your clock.
.TP
.B \-date <yyyymmdd>
Set the date to show sunrise/sunset for.
.SH EXAMPLES
.TP
.B wmSun -lon 106.3 -lat 35.9
this would display rise/set times at Los Alamos in local time.
.TP
.B wmSun -lat 19.58 -lon 155.92 -td 10 
this would display rise/set times in Kona, Hawaii in local time (in winter -- you need to
take into account daylight savings at other times of the year).
.SH BUGS
Who knows? (Let me know if you find any).
.SH AUTHOR
Michael G. Henderson <mghenderson@lanl.gov>
