.TH WMACPI-NG 1 "July 11, 2003"
.SH NAME
wmacpi-ng \- Battery status monitor for systems supporting ACPI
.SH NAME
acpi-ng \- Query battery status for systems supporting ACPI
.SH SYNOPSIS
.B wmacpi-ng
[
.RI -b
]
[
.RI -c
value ]
[
.RI -d
display ]
[
.RI -m
battery no ]
[
.RI -v
]
]
.RI -n
]
[
.RI -V
]
[
.RI -h
]
.PP
.B acpi-ng
[
.RI -a
samples ]
[
.RI -v 
]
[
.RI -V
]
[
.RI -h
]
.SH DESCRIPTION
This manual page documents briefly the
.B wmacpi-ng
command.
.PP
.B wmacpi-ng
is a program that displays the current battery status in a WindowMaker
dock app, on systems that support Intel's Advanced Configuration and
Power Interface specification (ACPI).
.PP
The program monitors a battery, displaying its current percentage
charge via a bar and a numeric value. It also displays the current
power status for the system, the time remaining (calculated based on
the remaining battery capacity and the current rate of power usage),
and a scrolling message with some hopefully useful information.
.PP
Clicking on the window cycles through the batteries that the ACPI
system knows about.
.PP
.B acpi-ng
queries the battery status from the command line. It prints the power
status, the percentage remaining for each battery found, and the time
remaining if the system is on battery, or the time remaining for each
battery to reach full charge if the batteries are charging.
.SH OPTIONS
.B wmacpi-ng
.TP
.B \-b
Make noise when battery is critical low (beep).
.TP
.B \-c value
Set critical low alarm at <value>% (default: 10%).
.TP
.B \-d
Set the X display to open the window on.
.TP
.B \-m
Set the battery to monitor initially.
.TP
.B \-n
Disable blinking power glyph when charging. Note that it still blinks when 
the battery reports its capacity state as critical.
.B \-v
Increase the verbosity of the program. Can be used more than once -
each successive use increases the verbosity.
.TP
.B \-V
Print the version information.
.TP
.B \-h
Display help.
.TP
.B acpi-ng
.TP
.B \-a num
Average the time remaining over num samples. This greatly improves the
accuracy of the reported time remaining.
.TP
.B \-v
Increase the verbosity of the program, as for
.B wmacpi-ng
.TP
.B \-V
Print the version information.
.TP
.B \-h
Display help.
.TP
.SH SEE ALSO
.BR wmapm (1)
.br
.SH AUTHOR
.B wmacpi
as written by Tim Copperfield <timecop@japan.co.jp>. 
.B wmacpi-ng 
is a reworking of 
.B wmacpi 1.34
to support recent kernel versions, performed by Simon Fowler
<simon@dreamcraft.com.au>. 
.PP
This manual page was originally written by Simon Richter
<sjr@debian.org> for the Debian GNU/Linux system, and then updated for 
.B wmacpi-ng
by Simon Fowler.
.br
Last modification by Simon Fowler <simon@dreamcraft.com.au>, 2003-07-11.
