.TH wmitime 1 "2014-12-19" "wmitime" "User Commands"
.SH "NAME"
wmitime \- Window Maker dock app displaying date, clock and internet time
.SH "SYNOPSIS"
.B wmitime
[\fI\,options\/\fR]
.SH "DESCRIPTION"
WMitime is yet another clock dock app, which shows standard time,
date, as well as the new internet time <http://www.swatch.com/>.
.SH "OPTIONS"
.TP
\fB\-12\fR
12\-hour mode
.TP
\fB\-display\fR <display name>
Specify X display
.TP
\fB\-geometry\fR +XPOS+YPOS
Initial window position.
.TP
\fB\-l\fR <locale>
Specify locale.
.TP
\fB\-h\fR
Print available options.
.TP
\fB\-v\fR
Print the version number.
.SH "SEE ALSO"
.BR wmtime (1)
.SH "AUTHORS"
This manual page was written by Lenart Janos <ocsi@debian.org>, for
the Debian GNU system (but may be used by others). Updated by Jari
Aalto <jari.aalto@cante.net>.
