.TH WMUSIC 1 "February 22, 2002"
.SH NAME
wmusic \- a remote-control DockApp for xmms
.SH SYNOPSIS
.B wmusic
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B wmusic command.
\fBwmusic\fP is a dockapp that remote-controls xmms. Features include
VCR-style controls, Time and Playlist display, supa stylee rotating
arrow, hiding of the xmms windows and reactive interface.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.TP
.B \-c, \-\-command <program>
Use <program> as the command to launch XMMS. You can start XMMS
by a double-click into the status part of \fBwmusic\fP.
.TP
.B \-d, \-\-display host:display[.screen]
specifies the X server to contact; see X(1).
.TP
.B \-r, \-\-run
Run XMMS on startup.
.TP
.B \-R, \-\-run\-exclusive
Run XMMS on startup, exit when xmms exits.
.TP
.B \-s, \-\-session <number>
Wich XMMS Session to use.
.TP
.B \-t, \-\-title
Shows title instead of kbps by default.
.TP
.B \-u, \-\-hide
Hide XMMS windows on startup.
.TP
.B \-V, \-\-volume
Stepping of the wheel volume control (in percent).
.TP
.B \-x, \-\-wmxmms
Use wmxmms-like show and hide. Just hide the main XMMS window.
If you do not use this parameter, \fBwmusic\fP show and hide
the main, playlist and equaliser windows. You can toggle the hide
function by pressing with the middle button into the status part of
\fBwmusic\fP.
.TP
.B \-w, \-\-windowed
Run in windowed mode. Use this, if you want to run \fBwmusic\fP in
the AfterStep wharf.
.TP
.B \-a, \-\-rotate-arrow
Stop the rotating arrow when \fBwmusic\fP is paused.
.TP
.B \-l, \-\-time-left
Start \fBwmusic\fP with the display showing time left instead of time
elapsed.
.SH SEE ALSO
.BR xmms (1x), wmaker (1x)
.SH AUTHOR
wmusic was originally written by Bastien Nocera <hadess@hadess.net> and 
it is now maintained by John Chapin <john+wmusic@jtan.com>.
This manual page was written by Alain Schroeder <alain@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
