.\"                                      Hey, EMACS: -*- nroff -*-
.\" wmxres.1 is copyright 2001 by
.\" Todd Troxell <ttroxell@debian.org>
.\"
.\" This is free documentation, see the latest version of the GNU
.\" General Public License for copying conditions. There is NO warranty.
.TH WMXRES 1 "May  5, 2001"

.SH NAME
wmxres \- dockable application to change X modes

.SH SYNOPSIS
.B wmxres

.SH DESCRIPTION
dockable application to select your display mode from those available.  It is written in C.

.SH INFO
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.PP

.SH AUTHOR
This manual page was written by Todd Troxell <ttroxell@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
