.\"                                      Hey, EMACS: -*- nroff -*-
.\"
.\" This documentation may be distributed under the terms of
.\" the GNU General Public Licence version 2.
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH wmmisc 1 "Sep 10, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wmmisc \- Dock app that monitors your system
.SH SYNOPSIS
.B wmmisc
.RI "{ " options " }"
.SH DESCRIPTION
.B wmmisc
is a simple dockapp that monitors the following:
the amount of users logged in, the total number of
processes, the number of running (or 'alive') processes,
the total number of forks and the system load average.
.SH OPTIONS
.TP
.BI "\-v "
Output version information and exit
.TP
.B \-h
Display help and exit

.SH BUGS
Report bugs and suggestion to the current \fBwmmisc\fR maintainer:
Jesse S. <luxorfalls@sbcglobal.net>.
.SH SEE ALSO
.BR wmaker (1x).
.SH AUTHOR
This manual page was written by Vincent Tantardini <vinc@sceen.net>.
The original \fBwmmisc\fR authour is  Jesse S. <luxorfalls@sbcglobal.net>.
