.TH wmshutdown 1 2014-10-25
.SH NAME
wmshutdown \-A graphical dock application to shutdown computer
.SH SYNOPSIS
wmshutdown [OPTIONS]
.SH DESCRIPTION
wmshutdown is a dock application (for Window Maker) that can shut down or
reboot the workstation by clicking a button on the desktop.  It uses logind.
.SH OPTIONS
.TP
\fB-h\fR, \fB\-\-help\fR
Show help options
.TP
\fB-v\fR, \fB\-\-version\fR
Display version information
.TP
\fB\-\-display=\fIDISPLAY\fR
X display to use
.SH SEE ALSO
\fBsystemd-logind\fR(8)
.SH AUTHORS
wmshutdown was written by Rafael V. Aroca <rafael@linuxqos.cjb.net> and
is currently maintained by Doug Torrance <dtorrance@monmouthcollege.edu>.
This manual page was adapted from the one written by Jari Aalto
<jari.aalto@cante.net> for Debian.
