.TH WMCDplay 1 "December 18, 2014"
.SH NAME
wmcdplay \- A cd player designed for WindowMaker
.SH SYNOPSIS
.B wmcdplay
.RI [ options ]
.br
.SH DESCRIPTION
A skinable CD player for the Window Maker dock.
.SH OPTIONS
.TP
\fB\-h\fR | \fB\-help\fR | \fB\-\-help\fR
display this help screen
.TP
\fB\-w\fR
use WithdrawnState (for WindowMaker)
.TP
\fB\-s\fR
shaped window
.TP
\fB\-a\fR
use smaller window (for AfterStep Wharf)
.TP
\fB\-f\fR artwork_file
load the specified artwork file
.TP
\fB\-t\fR track_selection
set track selection (between 0 and 4)
.TP
\fB\-v\fR volume
set the cdrom volume (between 0 and 255)
.TP
\fB\-i\fR interval
interval in 1/20 seconds between cd polls when empty
.TP
\fB\-l\fR led_color
use the specified color for led displays
.TP
\fB\-b\fR back_color
use the specified color for backgrounds
.TP
\fB\-d\fR cd_device
use specified device
.TP
\fB\-position\fR position
set window position
.TP
\fB\-display\fR display
select target display
.SH AUTHOR
wmcdplay was written by Sam Hawker <shawkie@geocities.com>

This manual page was written by John H. Robinson, IV <jaqque@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
.
