/* XPM */
static char * dock_master[] = {
"64 64 74 1",
" 	c None",
".	c #F7FBFF",
"+	c #F7F7FF",
"@	c #EFF7FF",
"#	c #EFF3FF",
"$	c #EFEFFF",
"%	c #EBF4FC",
"&	c #EBEFFC",
"*	c #EBEBFC",
"=	c #E2EBF3",
"-	c #E2E6F3",
";	c #E2E2F3",
">	c #E3E3EB",
",	c #DAE3EB",
"'	c #DADEEB",
")	c #DADAEB",
"!	c #DBDBE3",
"~	c #D2DBE3",
"{	c #D2D6E3",
"]	c #A8ACB9",
"^	c #000000",
"/	c #545865",
"(	c #A8A8B9",
"_	c #9FA8B0",
":	c #9FA3B0",
"<	c #9F9FB0",
"[	c #97A0A8",
"}	c #979BA8",
"|	c #9797A8",
"1	c #97979F",
"2	c #8E979F",
"3	c #8E929F",
"4	c #8E8E9F",
"5	c #8F8F97",
"6	c #868F97",
"7	c #868A97",
"8	c #868697",
"9	c #7E878F",
"0	c #7E828F",
"a	c #191919",
"b	c #DACDC9",
"c	c #7E7E8F",
"d	c #545465",
"e	c #757E86",
"f	c #4B545C",
"g	c #757986",
"h	c #4B4F5C",
"i	c #757586",
"j	c #4B4B5C",
"k	c #6D767E",
"l	c #4C4C54",
"m	c #434C54",
"n	c #6D717E",
"o	c #434754",
"p	c #6D6D7E",
"q	c #434354",
"r	c #6E6E76",
"s	c #44444C",
"t	c #656E76",
"u	c #3B444C",
"v	c #656976",
"w	c #3B3F4C",
"x	c #656576",
"y	c #65656D",
"z	c #3B3B4C",
"A	c #5C656D",
"B	c #323B43",
"C	c #5C606D",
"D	c #323643",
"E	c #5C5C6D",
"F	c #323243",
"G	c #545D65",
"H	c #2A333B",
"I	c #2A2E3B",
"..+++@@@#######$$%%%%&&&&&&**====-------;>,,,,'''''')!~~~~~{{{]^",
".+++@@@#######$$%%%%&&&&&&**====-------;>,,,,'''''')!~~~~~{{{{/^",
"++((((__::::::<<<<[[}}}}}}}|||12233333344456667777778889990000/^",
"++(((__::::::<<<<[[}}}}}}}|||122333333444566677777788899900000/^",
"+@((^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^00/^",
"@@(_^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaab0c/^",
"@@__^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabccd^",
"@#_:^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabccd^",
"##::^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabced^",
"##::^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabeef^",
"##::^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabeef^",
"##::^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabeef^",
"##::^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabegh^",
"##:<^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabggh^",
"#$<<^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabggh^",
"$$<<^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabggh^",
"$%<<^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabggh^",
"%%<[^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabggh^",
"%%[[^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabgij^",
"%%[}^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabiij^",
"%&}}^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabikj^",
"&&}}^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabkkl^",
"&&}}^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabkkm^",
"&&}}^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabkkm^",
"&&}}^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabknm^",
"&&}}^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabnno^",
"&*}|^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabnno^",
"**||^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabnno^",
"*=||^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabnno^",
"==|1^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabnno^",
"==12^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabnpo^",
"==22^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabppq^",
"=-23^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabprq^",
"--33^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabrrs^",
"--33^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabrtu^",
"--33^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabttu^",
"--33^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabttu^",
"--33^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabtvw^",
"--34^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabvvw^",
"-;44^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabvvw^",
";>44^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabvvw^",
">,45^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabvvw^",
",,56^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabvvw^",
",,66^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabvxw^",
",,66^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabxyz^",
",'67^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabyyz^",
"''77^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabyAB^",
"''77^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabAAB^",
"''77^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabAAB^",
"''77^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabACB^",
"''77^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabCCD^",
"')78^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabCCD^",
")!88^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabCCD^",
"!~88^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabCCD^",
"~~89^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabCCD^",
"~~99^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabCCD^",
"~~99^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabCEF^",
"~~90^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabEEF^",
"~{00^aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabEGH^",
"{{00bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbGGH^",
"{{0000ccceeeeggggggiikkkknnnnnnpprrtttvvvvvvxyyAAACCCCCCCEEGGGH^",
"{{000ccceeeeggggggiikkkknnnnnnpprrtttvvvvvvxyyAAACCCCCCCEEGGGGH^",
"]/////dddfffhhhhhhjjjlmmmooooooqqsuuuwwwwwwwzzBBBBDDDDDDFFHHHHI^",
"^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"};
