.TH WMACPI 1 "April 15 2004"
.SH NAME
wmacpi \- Battery status monitor for systems supporting ACPI
.SH NAME
acpi \- Query battery status for systems supporting ACPI
.SH SYNOPSIS
.B wmacpi
[
.RI -c
value ]
[
.RI -d
display ]
[
.RI -m
battery no ]
[
.RI -s
sample rate ]
[
.RI -v
]
]
.RI -n
]
[
.RI -w
]
[
.RI -a
samples ]
[
.RI -V
]
[
.RI -h
]
.PP
.B acpi
[
.RI -a
samples ]
[
.RI -v 
]
[
.RI -V
]
]
.RI -b
]
[
.RI -r
]
[
.RI -h
]
.SH DESCRIPTION
This manual page documents briefly the
.B wmacpi
command.
.PP
.B wmacpi
is a program that displays the current battery status in a WindowMaker
dock app, on systems that support Intel's Advanced Configuration and
Power Interface specification (ACPI).
.PP
The program monitors a battery, displaying its current percentage
charge via a bar and a numeric value. It also displays the current
power status for the system, the time remaining (calculated based on
the remaining battery capacity and the current rate of power usage),
and a scrolling message with some hopefully useful information.
.PP
Clicking on the window cycles through the batteries that the ACPI
system knows about.
.PP
.B acpi
queries the battery status from the command line. It prints the power
status, the percentage remaining for each battery found, and the time
remaining if the system is on battery, or the time remaining for each
battery to reach full charge if the batteries are charging.
.SH OPTIONS
.B wmacpi
.TP
.B \-c percentage
Set critical low alarm at <value>% (default: 10%).
.TP
.B \-d display
Set the X display to open the window on.
.TP
.B \-m battery number
Set the battery to monitor initially.
.TP
.B \-s sample rate
Set the rate at which to sample the ACPI data, in number of times per
minute. Minimum is 1, ie once a minute, default is 20, maximum is 600.
.TP
.B \-n
Disable blinking power glyph when charging. Note that it still blinks when 
the battery reports its capacity state as critical.
.TP
.B \-w
Run wmacpi in command line mode - this operates identically to 
.B acpi
..
.TP
.B \-a num
Average the time remaining over num samples. This greatly improves the
accuracy of the reported time remaining.
.TP
.B \-v
Increase the verbosity of the program. Can be used more than once -
each successive use increases the verbosity.
.TP
.B \-V
Print the version information.
.TP
.B \-b
Enable blinking of the power glyph when charging the batteries.
.TP
.B \-r
Disable scrolling message.
.TP
.B \-h
Display help.
.TP
.B acpi
.TP
.B \-a num
Average the time remaining over num samples. This greatly improves the
accuracy of the reported time remaining.
.TP
.B \-v
Increase the verbosity of the program, as for
.B wmacpi
.TP
.B \-V
Print the version information.
.TP
.B \-h
Display help.
.TP
.SH SEE ALSO
.BR wmapm (1)
.br
.SH AUTHOR
.B wmacpi
was originally written by Tim Copperfield <timecop@japan.co.jp>, then
completely rewritten after 1.34 by Simon Fowler <simon@dreamcraft.com.au>.
.PP
This manual page was originally written by Simon Richter
<sjr@debian.org> for the Debian GNU/Linux system, and then updated by
Simon Fowler. 
.br
Last modification by Simon Fowler <simon@dreamcraft.com.au>, 2004-04-15.
