.TH WMHDPLOP 1 "June 25, 2004"
.SH NAME
wmhdplop \- hard drive monitor dockapp
.SH SYNOPSIS
.B wmhdplop
.RI [ options ]
.SH DESCRIPTION
This manual page documents briefly the
.B wmhdplop
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
.PP
\fBwmhdplop\fP is a program that monitors hard drive activity and
displays it graphically in a dockapp.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
Please run wmhdplop \-h to get a summary of options.
.SH AUTHOR
This manual page was written by G\[:u]rkan Seng\[:u]n <gurkan@linuks.mine.nu>,
for the Debian project (but may be used by others).
