

#define STATUS_HAVE_FAN1
#define STATUS_HAVE_FAN2
#define STATUS_HAVE_FAN3
#define STATUS_HAVE_TEMP1
#define STATUS_HAVE_TEMP2
#define STATUS_HAVE_TEMP3
#define STATUS_HAVE_TEMP4
#define STATUS_HAVE_SWAP
#define STATUS_HAVE_DISC
#define STATUS_HAVE_CPU
#define STATUS_HAVE_MEM
#define STATUS_HAVE_NET_ETH0
#define STATUS_HAVE_NET_ETH1
#define STATUS_HAVE_NET_PPP0
#define STATUS_HAVE_NET_LO

