#!/bin/bash

# This file should not be modified -- make local changes to
# /etc/ppp/ip-up.local instead

LOGDEVICE=$6
REALDEVICE=$1

echo "$REALDEVICE" > /var/run/ppp-$LOGDEVICE.dev
[ -x /etc/ppp/ip-up.local ] && exec /etc/ppp/ip-up.local $*

/etc/sysconfig/network-scripts/ifup-post ifcfg-${LOGDEVICE}

exit 0
