# wmckgmail 1.1 : A dockapp to monitor the number of unread mails in a gmail inbox
# writteh by    : Sylvain Tremblay <stremblay@gmail.com>
# release date  : September 09, 2006

all::
	cd wmckgmail && make

install::
	cd wmckgmail && make install

install-man::
	cd wmckgmail && make install-man

