.TH WMWEATHER 1.1 "19 January 1999" 
.SH NAME
WMWEATHER \- Dockable  Weather Monitor
.SH SYNOPSIS
.B wmWeather -station <4-char station ID> [-h] [-display <Display>] [-metric] [-kPa] [-hPa] [-mmHg] [-beaufort] [-mps] [-delay <Time in Minutes>] [-bc <color>] [-tc <color>] [-lc <color>] [-dc <color>] [-wgc <color>]
.SH DESCRIPTION
.PP
wmWeather monitors local weather conditions (temperature, Dew Point, Pressure,
Humidity and Wind direction and speed).  The user needs to specify a
4-character `METAR station identifier code'. (The standardized METAR station
designations and current weather reports are designed for use by the aviation
community. Since most major cities have at least one airport, there is usually
one or more METAR stations in a given city.) You (obviously) need to be
connected to the internet and you also need to have wget installed (most linux
systems should have it already).  wmWeather will then attempt to download the
latest METAR report for the station of your choice (from the National Weather
Sevice run by NOAA).
.PP
You can toggles back and forth between imperial and metric units. I.e. between
(degrees Fareheight, inches of Mercury, and miles per hour) and (degrees
Celsius, millimeters of Mercury, and kilometers per hour). Any key press will
do this.
.PP
Also, a left double click will bring up the fully decoded METAR report up in
xmessage. And a right double click will force an immediate update (i.e.
wmWeather will attempt to grab the weather information).
.PP
When the wind speed turns red, this means that the wind is gusty and the listed
value is an average only. Similarly, a red direction indicates a variable wind
direction and the value given is the average direction.
.PP
To find out more about the METAR/TAF system and to find the METAR code for your
location, look at http://www.nws.noaa.gov/oso/oso1/oso12/metar.htm for NOAA's
"National Weather Service METAR/TAF Information" page. To determine what your
station ID is use the lookup utility at:
http://www.nws.noaa.gov/oso/siteloc.shtml.
.SH OPTIONS
.TP
.B \-h
Display list of command-line options.
.TP
.B \-display <display>
Use an alternate X Display.
.TP
.B \-station <4-char station ID> (or \-s <4-char station ID>)
This option tells wmWeather which METAR station to show data for.
.TP
.B \-metric (or \-m)
Display temperatures in degrees Celsius.
.TP
.B \-kPa
When toggled to Celsius, display  pressure in units of kPa.
.TP
.B \-hPa
When toggled to Celsius, display  pressure in units of hPa (i.e. milliBars).
.TP
.B \-mmHg
When toggled to Celsius, display  pressure in units of millimeters of Mercury. (This is
the default for Celsius when no other units are specified).
.TP
.B \-beaufort
When toggled to Celsius, display wind speeds on the "beaufort scale".
.TP
.B \-mps
When toggled to metric display, show windspeed in units of meters/second.
.TP
.B \-delay <Time in Minutes>
Override time (in minutes) between updates (default is 15 minutes). (Times are approximate.)
.TP
.B \-lc <color>
Set the color of the labels. (E.g. -lc red or -lc salmon or -lc #4523ff).
.TP
.B \-bc <color>
Set the background color. (#8e8e69 is LCD-ish).
.TP
.B \-dc <color>
Set the color of the data entries. 
.TP
.B \-tc <color>
Set the color of the station ID/update time header.
.TP
.B \-wgc <color>
Set the gusty-wind/variable-direction color. The wind speed indicator will turn
this color when the wind speed is gusty. (The value shown in this case is the
average speed).  Similarly, the wind direction indicator with change to this
color when the wind direction is variable. (The value shown in this case is the
average direction).
.SH BUGS
Let me know if/when you find any. 
.SH NOTES
Requires that a (fairly recent) version of wget be installed on your machine. 
You can download wget from "http://sunsite.auc.dk/wget/".
.SH AUTHOR
Michael G. Henderson <mghenderson@lanl.gov>
